version: '3.4'

services:
  parbatapp:
    image: parbatimage
    build:
      context: src/Parbat.Core.Services/
      dockerfile: ParbatCore/Dockerfile
    ports:
    - "9080:80"
    depends_on:
    - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "MyPass@1234"
      ACCEPT_EULA: "Y"
    ports:
    - "14331:1433"

