version: '3.4'

networks:
  parbat-network:

services:
  parbatapp:
    image: webapi
    build:
      context: src/Parbat.Core.Services
      dockerfile: Dockerfile
    ports:
    - "80:80"
    networks:
      - parbat-network
    depends_on:
    - db
  db:
    image: db
    build:
      context: .
      dockerfile: database/Dockerfile
      #ports:
      #  - "1433:1433"
    networks:
      - parbat-network
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
    mssqldata:
