version: '3.4'

networks:
  parbat-network:

services:
  parbatapp:
    environment:
    - ASPNETCORE_ENVIRONMENT:Development
    image: webapi
    build:
      context: .
      dockerfile: src/Parbat.Core.Services/ParbatCore/Dockerfile
    ports:
    - "8081:80"
    networks:
      - parbat-network
    depends_on:
    - db
  db:
    image: db
    build:
      context: .
      dockerfile: database/Dockerfile
      #ports:
      #  - "1433:1433"
    networks:
      - parbat-network
    volumes:
      - parbat-mssqldata:/var/opt/mssql

volumes:
    parbat-mssqldata:
