version: '3.4'

services:
  parbatapp:
    image: parbatimage
    build:
      context: src/Parbat.Core.Services/
      dockerfile: ParbatCore/Dockerfile
    ports:
    - "9080:80"
    depends_on:
    - db
  db:
    image: parbat_dbimage
    build:
      context: .
      dockerfile: database/Dockerfile
      #ports:
      #  - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
    mssqldata:
