version: '3.4'

networks:
  parbat-network:

services:
  parbatapp:
    image: parbat
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - DB_NAME=ParbatDB
    - DB_PASSWORD=MyPass@1234
    - DB_SERVER=db
    - DB_USERNAME=sa
    - DB_TYPE=SQL
    - TRUSTED=False
    build:
      context: ./src/Parbat.Core/
      dockerfile: Dockerfile
    ports:
    - "8081:80"
    networks:
      - parbat-network
    depends_on:
    - db
  db:
    image: db
    build:
      context: .
      dockerfile: database/Dockerfile
      #ports:
      #  - "1433:1433"
    networks:
      - parbat-network
    volumes:
      - parbat-mssqldata:/var/opt/mssql

volumes:
    parbat-mssqldata:
