# This is a basic workflow to help you get started with Actions

name: Test Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ mqp-docker ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOTNET_VERSION: '2.1.x'           # set this to the dot net version to use
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - uses: okteto/login@master
      with: 
        token: ${{secrets.OKTETO_TOKEN}}
          
    - name: "Activate namespace"
      uses: okteto/namespace@master
      with:
        name: parbat-mqpasta
        
    - name: "Okteto"
      uses: okteto/deploy-stack@master
      with:
        namespace: parbat-mqpasta
        build: "true"
        skipIfExists: true

